### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by tonyxue** [jadahl/www.jabber.se#28]
Don't know whether there's still someone looking after this project. Everything looks old here.
Here's the problem:

When I was compiling this program, everything seemed fine at the beginning but later on the "make" process was interrupted by an error:

`Compiled src/actions/action_update_table.erl
Compiled src/actions/action_state_panel.erl
make: *** [compile] Error 1`

I just can't figure out what's wrong with that.

Can anyone help me? Appreciate for that.

**Comment by jadahl** [comment]
Well, it's still running on www.jabber.se but just haven't done anything with it for a couple of years.

Anyhow, how did you go ahead building?

I looked at the README file, and it seems some points are missing.

For example, you need to fetch all the git submodules, using "git submodule update --init"

Then you need to build every individual package (no need to install, just build using make or equivalent)

After that you can run "make" in the root.

**Comment by tonyxue** [comment]
As i realised that there was something missing even I did git clone the www.jabber.se project, exactly as you said, the submodules in lib are missing. So I just got into the lib folder and did the  git clone of those projects manually, then I just installed them following the instructions in the README of www.jabber.se project. The installation of submodules were perfectly fine, but when I was installing the main application, it returned those errors.

**Comment by tonyxue** [comment]
I followed the steps again and with the command you gave me but it was still not working. The same error turned up. 
`Compiled src/actions/action_site.erl
make: *** [compile] Error 1`

**Comment by jadahl** [comment]
I tried it out here, and it seems to work when I tested. Are there no more relevant output? Anyway you can find out what command it is that is failing?

**Comment by tonyxue** [comment]
Is that I don't have some software that are required and they're not mentioned in README file? The only two things I have that I think are related to this project are  Yaws and Erlang... Did I miss anything?

And I noticed another error notice:
`src/actions/action_dialog.erl:none: error in parse transform 'gettext_compile':`

following are just bunch of things with brackets.

**Comment by tonyxue** [comment]
Oh... Wait, it works after I compiling the `gettext` in lib. It wasn't mentioned in README file... ;P

There're many submodules that are not mentioned in README to compile them, please update those :)
Anyway... Tack..

**Comment by tonyxue** [comment]
But when I run ./start.sh, it said `markdown.cpp` can't be found. How do I fix this?

`error: {badmatch,{error,{"no such file or directory","markdown.app"}}}`

**Comment by jadahl** [comment]
It probably say markdown.app not found. In erlmarkdown/src (or something) you can find a markdown.app.src. Copy that into the ebin directory of erlmarkdown. You also might need to create ebin/ there and copy the .beam files from src if necessary.

**Comment by jadahl** [comment]
Oh, and you need to rename it as well from markdown.app.src to markdown.app.

**Comment by tonyxue** [comment]
Sorry for keep disturbing you but it seems I'm having a hard time setting this up. Because I don't have the proper environment set up on my server since it's a brand new system.
 now I run `./start.sh` seems all the dependency problems are solved but I think I got a new kind of problem:
```(nitrogen@localhost)1> *\* lib/erlang-uuid/ebin/uuid.beam hides /usr/lib/erlang/lib/uuid-0.1.0/ebin/uuid.beam
*\* Found 1 name clashes in code paths 
info:db_controller:66:<0.105.0>: Opening database connection

=ERROR REPORT==== 10-Oct-2013::12:34:33 ===
    "Error when starting supervisor"
    error: {error,shutdown}```

What's supervisor mentioned in the report? Is that the system process state controlling tool?

**Comment by tonyxue** [comment]
Or it is the module of erlang?

**Comment by jadahl** [comment]
Could it be that couchdb is not running?

A supervisour is an Erlang concept, which more or less takes care of restarting services that crashes.

No worries, it'd be terrific if you'd get it running. You'd actually be the first not-me person doing so :)

**Comment by tonyxue** [comment]
Couchdb is running. What else should be running?

**Comment by jadahl** [comment]
Thats it. It should start its own http server (using yaws embedded).

I think I figured it out. You need to install yaws (in Debian, it's apt-get install yaws) and then update etc/start.conf.sh adding a "-pa /the/path/to/where/to/find/yaws/ebin" to there.

You also need to configure src/yaws_bundle.erl to point to some sane SSL certificate/key, because it's configured to always redirect to https then enabling "Strict-Transport-Security" which more or less means that encryption is required for the whole domain.

**Comment by jadahl** [comment]
You can disable the hard TLS requirement though, by commenting out some parts of the main() function in web_index.erl (the one about STS and redirecting). Maybe also some parts in yaws_bundle.erl so that it doesn't try to load the TLS files, but not sure that's a must.

**Comment by tonyxue** [comment]
Well, you were right about the Yaws, it wasn't configured properly.
But after doing what you've just told me, the same error still turned up... 
```=ERROR REPORT==== 10-Oct-2013::14:49:18 ===
    "Error when starting supervisor"
    error: {error,shutdown}

=INFO REPORT==== 10-Oct-2013::14:49:18 ===
    application: www_jabber_se
    exited: {bad_return,{{www_jabber_se_app,start,[normal,[]]},ok}}
    type: temporary

=ERROR REPORT==== 10-Oct-2013::14:49:18 ===
    "Error when starting www_jabber_se"
    error: {badmatch,
               {error,
                   {bad_return,{{www_jabber_se_app,start,[normal,[]]},ok}}}}
    stacktrace: [{www_jabber_se_app,start,0},
                 {init,start_it,1},
                 {init,start_em,1}]

```
```

**Comment by jadahl** [comment]
If you fire up "erl" and type
l(yaws).
yaws:start_embedded(".").

Does it work?

**Comment by jadahl** [comment]
Sorry, erl, but with the correct -pa of where to find yaws.beam, as you fixed in start.conf.sh

**Comment by tonyxue** [comment]
When I typed `l(yaws)` it returned `{error, nofile}`

Here's the command line copy:
``` erl -pa /usr/lib/yaws/custom/ebin
Erlang R14B04 (erts-5.8.5) [source] [smp:4:4] [rq:4] [async-threads:0] [kernel-poll:false]

Eshell V5.8.5  (abort with ^G)
1> 
1> l(yaws).
{error,nofile}
2> yaws:start_embedded(".").
*\* exception error: undefined function yaws:start_embedded/1 ```

**Comment by jadahl** [comment]
This means that yaws.beam is not found in /usr/lib/yaws/cutsom/ebin. Are you sure it's there?

**Comment by tonyxue** [comment]
Oh..... Sorry, my mistake, it's under /usr/lib/yaws/ebin, not /usr/lib/yaws/custom/ebin
I changed the setting in etc/start.conf.sh and ran ./start.sh again, It's working perfectly now! And the output only has INFO REPORT with Yaws listening info.

Thanks agian :)

**Comment by jadahl** [comment]
No problem, great that it worked out, finally :) Should probably fix the README so it actually describes how to get things going.

If you have any further question, don't hesitate to ask.
