### ISSUE TITLE
Where is the web server setting?

### ISSUE THREAD

**Issue by tonyxue** [jadahl/www.jabber.se#29]
Hi!

It's me again.

After starting ./start.sh , the yaws by default listen on only locahost. How do I assign other hostname for it to listen?
I modified the setting in include/config.hrl, changing the host and domain to my own domain name and I ran ./start.sh again but it's still listen on localhost only.

Thanks

**Comment by jadahl** [comment]
You can find some settings in include/config.hrl. Note that if you changed this, you need to re-save (or touch) src/cf_config.erl for it to take effect.

Long term goal is to not have settings in a .hrl file, but haven't gotten to it.

Some other settings are found in src/yaws_bundle.erl

**Comment by tonyxue** [comment]
I ran touch src/cf_config.erl and touch src/cf_config.erl -r include/config.hrl, but it still listens on localhost. Did i do it wrong?

**Comment by jadahl** [comment]
You mean it listnes to 127.0.0.1 ? That's odd, because AFAIKS it should listen on IPv6 address :: (which should be the IPv4 address 0.0.0.0 implicitly as well on Linux)

You can also configure the "hostname" and "domain" by changing -define(HOST, "localhost"). and -define(DOMAIN, "localhost") to something else (and then touch cf_config.erl, and recompile).

**Comment by tonyxue** [comment]
I did touch both cf_config.hrl and config.erl then ./configure&make but still, it listens on localhost.

I also tried to restart Yaws.

I'm not sure whether it is listening on 127.0.0.1 or ipv6, I haven't check yet. But the output from ./start.sh is still listen on localhost.

Any idea?

**Comment by jadahl** [comment]
Actually yaws will just say "localhost" either way. You can verify what address yaws is listening to using the "netstat" tool. Just type "netstat -ltnp" and look for the ports that is displayed in the log.

The hostname configured in config.hrl will mostly have affect when having enabled redirection (such as from http to https, or host.domain to www.host.domain) and for example the atom feed generator.

With no changes to web_index.erl, you can verify that the hostname setting work by observing the http to https redirection.

There is no support for running multiple web sites with only different domain in the same server right now.

**Comment by tonyxue** [comment]
Ok... seems now it's redirecting me to the right hostname now.

And by the way, how do I let the ./start.sh starting in the background silently? I'm using remote SSH connection to my server, so once I close the connection, the whole application stops running.

**Comment by jadahl** [comment]
Personally I just run it in a screen. You could try adding "-detached" to the variable in start.conf.sh, which should tell "erl" to detach and let the application run in the background.

**Comment by tonyxue** [comment]
ha! The website is up and running now and I'm just modifying some settings. But I still have two problems.

I am not able to change admin account name and password even I change them in the config.hrl, do I need to clean up couchdb or something? how?

Also, the content that compose through the website compose function is not showing. Seems like the only articles showing are those written in old_content.hrl.

By the way, the site is really simple and fast. I think if develop it further, it will another great web application. :)

**Comment by jadahl** [comment]
To change username and password you can use the couchdb web interface.

You can also use config.hrl, remove the couchdb database, rebuild db_controller.erl and regenerate the template content.

The content you compose needs the label "news" to show up in the front page.

To get some idea how that works, see src/content/content_news.erl, and in config.hrl look for MENU_ELEMENTS and DEFAULT_CONTENT_URL. In short, the default "url" is "news" which is translated to the Erlang module content_news, which calls cms:body(Title, "news"). The cms uses views to get content from the database, and a view corresponds more or less to a couchdb view. The "news" view is a view that fetches posts with the tag "news" in them. See db.hrl to see the different views. The content in the admin UI is done in a similar way.

I think the biggest problem with the project so far is that it has been developed more or less to build www.jabber.se, so a lot of stuff is hard coded. But I have had it in the back of my mind to make it reusable and if I'd ever get the time, split it up into a generic part not littered with jabber.se stuf. Also, where it is lacking the most is obviously installation and basic configuration :)

I have tried making it simple and fast, so glad to hear it is :) If you ever build something with it, it'd be nice to see :)

**Comment by tonyxue** [comment]
I failed to add a tag for my compose.

I filled in the tag name and then clicked publish, the content got published but the tags were not saved.

**Comment by tonyxue** [comment]
Another thing is even I commented the content in old_content.hrl, they are still showing.

**Comment by jadahl** [comment]
old_content.hrl is only read when creating the database. Removing the entries from old_content.hrl only has effect when running for the first time or running after removing the database. You should be able to remove them from the admin interface though, and also via couchdb web interface.

**Comment by jadahl** [comment]
Tags are saved by entering the tag, then pressing enter. If that doesn't work it's a bug.
